/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.match;

import form.datetimepicker.DateTimePicker;
import controller.Controller;
import domain.Match;
import domain.Odds;
import domain.Team;
import domain.Tip;
import form.FrmMain;
import form.FrmMode;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import session.Session;
import domain.GeneralEntity;

/**
 *
 * @author not-sure
 */
public class FrmMatch extends javax.swing.JDialog {
    DateTimePicker dateTimePicker;
    Match matchSearched = null;
    /**
     * Creates new form FrmMatch
     */
    public FrmMatch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public FrmMatch(FrmMain parent, boolean modal, FrmMode mode) {
        super(parent, modal);
        initComponents();
        setScreenCenter();
        adjustForm(mode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        pnlCurrnetUser = new javax.swing.JPanel();
        lblCurrentUser = new javax.swing.JLabel();
        pnlOdds = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtOdds5 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOdds23 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtOdds3 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtOdds01 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOdds1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOdds2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOddsX = new javax.swing.JTextPane();
        btnCreate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        lblMatchID = new javax.swing.JLabel();
        txtMatchID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        pnlTeams = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbHome = new javax.swing.JComboBox<>();
        txtHomeGoals = new javax.swing.JTextField();
        txtAwayGoals = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbAway = new javax.swing.JComboBox<>();
        txtTime = new javax.swing.JLabel();
        tpDate = new javax.swing.JTabbedPane();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCurrnetUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Current User"));

        javax.swing.GroupLayout pnlCurrnetUserLayout = new javax.swing.GroupLayout(pnlCurrnetUser);
        pnlCurrnetUser.setLayout(pnlCurrnetUserLayout);
        pnlCurrnetUserLayout.setHorizontalGroup(
            pnlCurrnetUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrnetUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCurrnetUserLayout.setVerticalGroup(
            pnlCurrnetUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrnetUserLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlOdds.setBorder(javax.swing.BorderFactory.createTitledBorder("Odds"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Number of goals"));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("0-1");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("2-3");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("3+");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("5+");

        txtOdds5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(txtOdds5);

        txtOdds23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane5.setViewportView(txtOdds23);

        txtOdds3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane6.setViewportView(txtOdds3);

        txtOdds01.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane7.setViewportView(txtOdds01);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Winner"));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("1");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("x");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("2");

        txtOdds1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(txtOdds1);

        txtOdds2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(txtOdds2);

        txtOddsX.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(txtOddsX);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlOddsLayout = new javax.swing.GroupLayout(pnlOdds);
        pnlOdds.setLayout(pnlOddsLayout);
        pnlOddsLayout.setHorizontalGroup(
            pnlOddsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOddsLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        pnlOddsLayout.setVerticalGroup(
            pnlOddsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOddsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOddsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnCreate.setText("Create Match");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert Score");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        lblMatchID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMatchID.setText("Match ID:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        pnlTeams.setBorder(javax.swing.BorderFactory.createTitledBorder("Teams"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("HOME");

        cmbHome.setMaximumRowCount(30);

        txtHomeGoals.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtAwayGoals.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("AWAY");

        cmbAway.setMaximumRowCount(30);

        javax.swing.GroupLayout pnlTeamsLayout = new javax.swing.GroupLayout(pnlTeams);
        pnlTeams.setLayout(pnlTeamsLayout);
        pnlTeamsLayout.setHorizontalGroup(
            pnlTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHomeGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAwayGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAway, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlTeamsLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(61, 61, 61))
        );
        pnlTeamsLayout.setVerticalGroup(
            pnlTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTeamsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHome)
                    .addComponent(txtHomeGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAwayGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAway))
                .addContainerGap())
        );

        txtTime.setText("Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMatchID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatchID, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(tpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCurrnetUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnlOdds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCurrnetUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatchID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatchID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsert)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(pnlOdds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        Team home = (Team)cmbHome.getSelectedItem();
        Team away = (Team)cmbAway.getSelectedItem();
        //System.out.println("Home "+home.getId()+", Away "+away.getId());
                
        if(home.equals(away)){
            JOptionPane.showMessageDialog(rootPane, "Match is not created! Teams must be different");
            return;
        }
                
        double odds1, oddsx, odds2, odds01, odds23, odds3, odds5;
        
        try{
            odds1 = Double.parseDouble(txtOdds1.getText().trim()); oddsx = Double.parseDouble(txtOddsX.getText().trim()); odds2 = Double.parseDouble(txtOdds2.getText().trim()); odds01 = Double.parseDouble(txtOdds01.getText().trim()); odds23 = Double.parseDouble(txtOdds23.getText().trim()); odds3 = Double.parseDouble(txtOdds3.getText().trim()); odds5 = Double.parseDouble(txtOdds5.getText().trim());
            if(!(odds1 >= 1 && oddsx >= 1 && odds2 >= 1 && odds01 >= 1 && odds23 >= 1 && odds3 >= 1 && odds5 >= 1)){
                JOptionPane.showMessageDialog(rootPane, "Match is not created! All odds can not be less than 1");
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Match is not created! All odds must be inserted as decimal values");
            return;
        }
        
        Date date = dateTimePicker.getDate();
        System.out.println(date.toString());
                
        if(!(date.after(new Date()))){
            JOptionPane.showMessageDialog(rootPane, "Match is not created! Date must be in future");
            return;
        }
        
        
        Match match = new Match(date, Session.getInstance().getCurreUser(), home, away);
        List<Odds> list = new LinkedList<>();
        list.add(new Odds(match, new Tip("1"), odds1));
        list.add(new Odds(match, new Tip("x"), oddsx));
        list.add(new Odds(match, new Tip("2"), odds2));
        list.add(new Odds(match, new Tip("0-1"), odds01));
        list.add(new Odds(match, new Tip("2-3"), odds23));
        list.add(new Odds(match, new Tip("3+"), odds3));
        list.add(new Odds(match, new Tip("5+"), odds5));
        try {
            match = Controller.getInstance().saveMatch(match, list);
        } catch (Exception ex) {
            Logger.getLogger(FrmMatch.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Match is not created! " + ex.getMessage());
            return;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Match is successfully created! ID: "+match.getId());
        resetForm();
        refreshDate();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        resetInsertScore();
        int id;
        try{
            id = Integer.parseInt(txtMatchID.getText().trim());
            if(id < 0)
                throw new Exception();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Score cannot be inserted! Match ID must be positive integer");
            return;
        }
        
        
        try {
            matchSearched = Controller.getInstance().getMatchForScoreInsert(id);
        } catch (Exception ex) {
            Logger.getLogger(FrmMatch.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Score cannot be inserted! " + ex.getMessage());
            return;
        }
        
        pnlTeams.setVisible(true);
        cmbHome.addItem(matchSearched.getHome());
        cmbAway.addItem(matchSearched.getAway());
        txtHomeGoals.setVisible(true);
        txtAwayGoals.setVisible(true);
        btnInsert.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        int goalsHome;
        
        try{
            goalsHome = Integer.parseInt(txtHomeGoals.getText().trim());
            if(goalsHome < 0)
                throw new Exception();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Score is not inserted! Number of goals for "+matchSearched.getHome().getName()+" must be nonnegative integer");
            return;
        }
        
        int goalsAway;
        
        try{
            goalsAway = Integer.parseInt(txtAwayGoals.getText().trim());
            if(goalsAway < 0)
                throw new Exception();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Score is not inserted! Number of goals for "+matchSearched.getAway().getName()+" team must be nonnegative integer");
            return;
        }
        
        matchSearched.setScoreInserted(true);
        matchSearched.setGoalsHome(goalsHome);
        matchSearched.setGoalsAway(goalsAway);
        
        
        try {
            Controller.getInstance().saveScore(matchSearched);
        } catch (Exception ex) {
            Logger.getLogger(FrmMatch.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Score is not inserted! "+ex.getMessage());
            return;
        }
        
        
        JOptionPane.showMessageDialog(rootPane, "Score is successfully inserted!");
        
        resetInsertScore();
        txtMatchID.setText("");
    }//GEN-LAST:event_btnInsertActionPerformed

    private void setScreenCenter() {
        setLocationRelativeTo(null);
    }

    private void adjustForm(FrmMode mode) {
        populateCurrentUser();
        populateDate();
        
        
        switch(mode){
            case NEW:
                lblMatchID.setVisible(false);
                txtMatchID.setVisible(false);
                btnSearch.setVisible(false);
                txtHomeGoals.setVisible(false);
                txtAwayGoals.setVisible(false);
                btnInsert.setVisible(false);
                setTitle("New match");
                populateCmbTeams();
                
                break;
            case INSERTRESULT:
                tpDate.setVisible(false);
                btnCreate.setVisible(false);
                pnlOdds.setVisible(false);
                txtTime.setVisible(false);
                setTitle("Insert score");
                pnlTeams.setVisible(false);
                btnInsert.setVisible(false);
                
                break;
        }
        

    }

    private void populateCurrentUser() {
        lblCurrentUser.setText(Session.getInstance().getCurreUser().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Team> cmbAway;
    private javax.swing.JComboBox<Team> cmbHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblMatchID;
    private javax.swing.JPanel pnlCurrnetUser;
    private javax.swing.JPanel pnlOdds;
    private javax.swing.JPanel pnlTeams;
    private javax.swing.JTabbedPane tpDate;
    private javax.swing.JTextField txtAwayGoals;
    private javax.swing.JTextField txtHomeGoals;
    private javax.swing.JTextField txtMatchID;
    private javax.swing.JTextPane txtOdds01;
    private javax.swing.JTextPane txtOdds1;
    private javax.swing.JTextPane txtOdds2;
    private javax.swing.JTextPane txtOdds23;
    private javax.swing.JTextPane txtOdds3;
    private javax.swing.JTextPane txtOdds5;
    private javax.swing.JTextPane txtOddsX;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    private void populateDate() {
        Date date = new Date();
        dateTimePicker = new DateTimePicker();
        dateTimePicker.setFormats(DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM));
        dateTimePicker.setTimeFormat(DateFormat.getTimeInstance(DateFormat.MEDIUM));
        dateTimePicker.setDate(date);
        tpDate.add(dateTimePicker);
    }
    
    private void refreshDate(){
        Date date = new Date();       
        dateTimePicker.setDate(date);       
        try {
            dateTimePicker.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(FrmMatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private void populateCmbTeams() {
        cmbHome.removeAllItems();
        cmbAway.removeAllItems();
        List<GeneralEntity> list = null;
        
        try {
            list = Controller.getInstance().getAllTeams();
        } catch (Exception ex) {
            Logger.getLogger(FrmMatch.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        list.sort((a, b) -> ((Team)a).getName().compareTo(((Team)b).getName()));
        
        for(GeneralEntity t : list){
            cmbHome.addItem((Team)t);
            cmbAway.addItem((Team)t);
        }
        
        cmbHome.setSelectedIndex(0);
        cmbAway.setSelectedIndex(1);
    }

    private void resetForm() {
        populateCmbTeams();
        txtAwayGoals.setText("");
        txtHomeGoals.setText("");
        txtOdds01.setText("");
        txtOdds1.setText("");
        txtOdds2.setText("");
        txtOdds23.setText("");
        txtOdds3.setText("");
        txtOdds5.setText("");
        txtOddsX.setText("");
    }

    private void resetInsertScore() {
        matchSearched = null;
        cmbHome.removeAllItems();
        cmbAway.removeAllItems();
        txtHomeGoals.setText("");
        txtAwayGoals.setText("");
        txtHomeGoals.setVisible(false);
        txtAwayGoals.setVisible(false);
        pnlTeams.setVisible(false);
        btnInsert.setVisible(false);
    }
}
